**Patrick Canny 
EECS731 
Intro to Data Cleaning**

For this first project, I decided to look at data from the Earth Science industry. Specifically, I was interested in looking into how water is being used around the world, and decided to heavily focus on the AQUASTAT datasets in this project.

I found this short article regarding 5 countries using new an innovative water technologies, and figured that it would be interesting to look at the two of these countries from an agricultural water usage perspective. Using the Tools on AQUASTAT, decided to grab all of the water data from 1978 to the present for both of these countries. 

The datasets that I have selected come from AQUASTAT: http://www.fao.org/nr/water/aquastat/data/query/index.html?lang=en

In [1]:
# Set up imports for pandas, numpy, and matplotlib per 10min guide.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Create new dataframe for each of the two datasets
saudi_arabia = pd.read_csv("../data/raw/saudi_arabia.csv",
                          usecols=['Area','Area Id','Variable Name','Variable Id','Year','Value','Symbol','Md'])
usa = pd.read_csv("../data/raw/usa.csv",
                 usecols=['Area','Area Id','Variable Name','Variable Id','Year','Value','Symbol','Md'])

In [3]:
# clean off metadata entries
usa = usa.loc[~(usa['Area'] != "United States of America")]
saudi_arabia = saudi_arabia.loc[~(saudi_arabia['Area'] != "Saudi Arabia")]

In [4]:
# remove unhelpful columns
del usa['Symbol']
del usa['Md']
del saudi_arabia['Symbol']
del saudi_arabia['Md']

In [5]:
usa

,Area,Area Id,Variable Name,Variable Id,Year,Value
0,United States of America,231.0,Total area of the country,4100.0,1982.0,962909.000
1,United States of America,231.0,Total area of the country,4100.0,1987.0,962909.000
2,United States of America,231.0,Total area of the country,4100.0,1992.0,962909.000
3,United States of America,231.0,Total area of the country,4100.0,1997.0,962909.000
4,United States of America,231.0,Total area of the country,4100.0,2002.0,963203.000
5,United States of America,231.0,Total area of the country,4100.0,2007.0,963203.000
6,United States of America,231.0,Total area of the country,4100.0,2012.0,983151.000
7,United States of America,231.0,Total area of the country,4100.0,2014.0,983151.000
8,United States of America,231.0,Arable land area,4101.0,1982.0,187765.000
9,United States of America,231.0,Arable land area,4101.0,1987.0,185742.000
10,United States of America,231.0,Arable land area,4101.0,1992.0,184080.000
11,United States of America,231.0,Arable land area,4101.0,1997.0,177592.000
12,United States of America,231.0,Arable land area,4101.0,2002.0,172977.000
13,United States of America,231.0,Arable land area,4101.0,2007.0,161880.000
14,United States of America,231.0,Arable land area,4101.0,2012.0,155108.000
15,United States of America,231.0,Arable land area,4101.0,2014.0,154605.000
16,United States of America,231.0,Permanent crops area,4102.0,1982.0,2034.000
17,United States of America,231.0,Permanent crops area,4102.0,1987.0,2034.000
18,United States of America,231.0,Permanent crops area,4102.0,1992.0,2100.000
19,United States of America,231.0,Permanent crops area,4102.0,1997.0,2500.000
20,United States of America,231.0,Permanent crops area,4102.0,2002.0,2730.000
21,United States of America,231.0,Permanent crops area,4102.0,2007.0,2600.000
22,United States of America,231.0,Permanent crops area,4102.0,2012.0,2600.000
23,United States of America,231.0,Permanent crops area,4102.0,2014.0,2600.000
24,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1982.0,189799.000
25,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1987.0,187776.000
26,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1992.0,186180.000
27,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1997.0,180092.000
28,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,2002.0,175707.000
29,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,2007.0,164480.000
...,...,...,...,...,...,...
580,United States of America,231.0,Conservation agriculture area,4454.0,2002.0,22400.000
581,United States of America,231.0,Conservation agriculture area,4454.0,2007.0,26500.000
582,United States of America,231.0,Conservation agriculture area,4454.0,2009.0,35613.000
583,United States of America,231.0,Conservation agriculture area as % of arable l...,4455.0,1984.0,2.584
584,United States of America,231.0,Conservation agriculture area as % of arable l...,4455.0,1991.0,3.715
585,United States of America,231.0,Conservation agriculture area as % of arable l...,4455.0,1997.0,9.776
586,United States of America,231.0,Conservation agriculture area as % of arable l...,4455.0,2002.0,12.950
587,United States of America,231.0,Conservation agriculture area as % of arable l...,4455.0,2007.0,16.370
588,United States of America,231.0,Conservation agriculture area as % of arable l...,4455.0,2009.0,22.960
589,United States of America,231.0,Area salinized by irrigation,4400.0,1987.0,4200.000
590,United States of America,231.0,% of area equipped for irrigation salinized,4445.0,1987.0,15.750
591,United States of America,231.0,Flood occurrence (WRI),4543.0,2013.0,3.100
592,United States of America,231.0,Total population with access to safe drinking-...,4114.0,1992.0,98.500
593,United States of America,231.0,Total population with access to safe drinking-...,4114.0,1997.0,98.700
594,United States of America,231.0,Total population with access to safe drinking-...,4114.0,2002.0,98.900
595,United States of America,231.0,Total population with access to safe drinking-...,4114.0,2007.0,99.000
596,United States of America,231.0,Total population with access to safe drinking-...,4114.0,2012.0,99.100
597,United States of America,231.0,Total population with access to safe drinking-...,4114.0,2015.0,99.200
598,United States of America,231.0,Rural population with access to safe drinking-...,4115.0,1992.0,94.400
599,United States of America,231.0,Rural population with access to safe drinking-...,4115.0,1997.0,95.300
600,United States of America,231.0,Rural population with access to safe drinking-...,4115.0,2002.0,96.200
601,United States of America,231.0,Rural population with access to safe drinking-...,4115.0,2007.0,97.100
602,United States of America,231.0,Rural population with access to safe drinking-...,4115.0,2012.0,98.000
603,United States of America,231.0,Rural population with access to safe drinking-...,4115.0,2015.0,98.200
604,United States of America,231.0,Urban population with access to safe drinking-...,4116.0,1992.0,99.700
605,United States of America,231.0,Urban population with access to safe drinking-...,4116.0,1997.0,99.700
606,United States of America,231.0,Urban population with access to safe drinking-...,4116.0,2002.0,99.600
607,United States of America,231.0,Urban population with access to safe drinking-...,4116.0,2007.0,99.500
608,United States of America,231.0,Urban population with access to safe drinking-...,4116.0,2012.0,99.400
609,United States of America,231.0,Urban population with access to safe drinking-...,4116.0,2015.0,99.400

In [6]:
saudi_arabia

,Area,Area Id,Variable Name,Variable Id,Year,Value
0,Saudi Arabia,194.0,Total area of the country,4100.0,1982.0,214969.0000
1,Saudi Arabia,194.0,Total area of the country,4100.0,1987.0,214969.0000
2,Saudi Arabia,194.0,Total area of the country,4100.0,1992.0,214969.0000
3,Saudi Arabia,194.0,Total area of the country,4100.0,1997.0,214969.0000
4,Saudi Arabia,194.0,Total area of the country,4100.0,2002.0,214969.0000
5,Saudi Arabia,194.0,Total area of the country,4100.0,2007.0,214969.0000
6,Saudi Arabia,194.0,Total area of the country,4100.0,2012.0,214969.0000
7,Saudi Arabia,194.0,Total area of the country,4100.0,2014.0,214969.0000
8,Saudi Arabia,194.0,Arable land area,4101.0,1982.0,1990.0000
9,Saudi Arabia,194.0,Arable land area,4101.0,1987.0,2900.0000
10,Saudi Arabia,194.0,Arable land area,4101.0,1992.0,3650.0000
11,Saudi Arabia,194.0,Arable land area,4101.0,1997.0,3639.0000
12,Saudi Arabia,194.0,Arable land area,4101.0,2002.0,3600.0000
13,Saudi Arabia,194.0,Arable land area,4101.0,2007.0,3446.0000
14,Saudi Arabia,194.0,Arable land area,4101.0,2012.0,3117.0000
15,Saudi Arabia,194.0,Arable land area,4101.0,2014.0,3502.0000
16,Saudi Arabia,194.0,Permanent crops area,4102.0,1982.0,78.0000
17,Saudi Arabia,194.0,Permanent crops area,4102.0,1987.0,80.0000
18,Saudi Arabia,194.0,Permanent crops area,4102.0,1992.0,96.0000
19,Saudi Arabia,194.0,Permanent crops area,4102.0,1997.0,146.0000
20,Saudi Arabia,194.0,Permanent crops area,4102.0,2002.0,193.0000
21,Saudi Arabia,194.0,Permanent crops area,4102.0,2007.0,229.0000
22,Saudi Arabia,194.0,Permanent crops area,4102.0,2012.0,228.0000
23,Saudi Arabia,194.0,Permanent crops area,4102.0,2014.0,145.2000
24,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1982.0,2068.0000
25,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1987.0,2980.0000
26,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1992.0,3746.0000
27,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1997.0,3785.0000
28,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,2002.0,3793.0000
29,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,2007.0,3675.0000
...,...,...,...,...,...,...
481,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Citrus,4362.0,1999.0,8.0280
482,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Citrus,4362.0,2006.0,10.8500
483,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Oil palm,4370.0,1992.0,2.7000
484,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Other...,4378.0,1992.0,95.5000
485,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Other...,4378.0,1999.0,175.5000
486,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Other...,4378.0,2006.0,190.8000
487,Saudi Arabia,194.0,% of total grain production irrigated,4329.0,1992.0,100.0000
488,Saudi Arabia,194.0,Total cultivated area drained,4300.0,2007.0,10.8500
489,Saudi Arabia,194.0,% of total cultivated area drained,4305.0,1992.0,1.1740
490,Saudi Arabia,194.0,% of total cultivated area drained,4305.0,2007.0,0.2952
491,Saudi Arabia,194.0,Area waterlogged by irrigation,4401.0,1980.0,15.0000
492,Saudi Arabia,194.0,Flood occurrence (WRI),4543.0,2013.0,1.2000
493,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,1992.0,92.3000
494,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,1997.0,94.0000
495,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2002.0,95.7000
496,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2007.0,97.0000
497,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2012.0,97.0000
498,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2015.0,97.0000
499,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,1992.0,92.3000
500,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,1997.0,94.0000
501,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2002.0,95.7000
502,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2007.0,97.0000
503,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2012.0,97.0000
504,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2015.0,97.0000
505,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,1992.0,92.3000
506,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,1997.0,94.0000
507,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2002.0,95.7000
508,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2007.0,97.0000
509,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2012.0,97.0000
510,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2015.0,97.0000

In [7]:
# need to save copies of these processed dataframes
usa.to_csv('../data/processed/usa_p.csv', compression='gzip')
saudi_arabia.to_csv('../data/processed/saudi_arabia_p.csv', compression='gzip')

At this point, the datasets still have a lof of information that could be well utilized to generate meaningful knowledge. The next step will be to try and transform these two seperate data frames into a singular dataset, perhaps based on the values in the 'Variable Name' field.

I have a few ideas on how to condense this data into more useful knowledge
1. Create a new dataframe comparing the USA and Saudi Arabia on each of the values in the 'Variable Name' field. This would allow a head to head comparison of these two countries and their ability to provide clean water and resources for citizens. 
2. Determine the change in one of the fields over time for both countries and compare their growth over time

I think I will take the first approach this time around, since this assignment seems to be more related to transforming data than it is to start building models and processing data.

In [9]:
# I used a simple join to combine the two tables into one
combinedDF = usa.join(saudi_arabia, lsuffix='_usa', rsuffix='_sa')

In [12]:
# Some data is not avilable for both countries, so I removed the entries that were NaN
combinedDF = combinedDF[pd.notnull(combinedDF['Variable Id_sa'])]

In [13]:
# Show the new DF
combinedDF

,Area_usa,Area Id_usa,Variable Name_usa,Variable Id_usa,Year_usa,Value_usa,Area_sa,Area Id_sa,Variable Name_sa,Variable Id_sa,Year_sa,Value_sa
0,United States of America,231.0,Total area of the country,4100.0,1982.0,962909.000,Saudi Arabia,194.0,Total area of the country,4100.0,1982.0,214969.0000
1,United States of America,231.0,Total area of the country,4100.0,1987.0,962909.000,Saudi Arabia,194.0,Total area of the country,4100.0,1987.0,214969.0000
2,United States of America,231.0,Total area of the country,4100.0,1992.0,962909.000,Saudi Arabia,194.0,Total area of the country,4100.0,1992.0,214969.0000
3,United States of America,231.0,Total area of the country,4100.0,1997.0,962909.000,Saudi Arabia,194.0,Total area of the country,4100.0,1997.0,214969.0000
4,United States of America,231.0,Total area of the country,4100.0,2002.0,963203.000,Saudi Arabia,194.0,Total area of the country,4100.0,2002.0,214969.0000
5,United States of America,231.0,Total area of the country,4100.0,2007.0,963203.000,Saudi Arabia,194.0,Total area of the country,4100.0,2007.0,214969.0000
6,United States of America,231.0,Total area of the country,4100.0,2012.0,983151.000,Saudi Arabia,194.0,Total area of the country,4100.0,2012.0,214969.0000
7,United States of America,231.0,Total area of the country,4100.0,2014.0,983151.000,Saudi Arabia,194.0,Total area of the country,4100.0,2014.0,214969.0000
8,United States of America,231.0,Arable land area,4101.0,1982.0,187765.000,Saudi Arabia,194.0,Arable land area,4101.0,1982.0,1990.0000
9,United States of America,231.0,Arable land area,4101.0,1987.0,185742.000,Saudi Arabia,194.0,Arable land area,4101.0,1987.0,2900.0000
10,United States of America,231.0,Arable land area,4101.0,1992.0,184080.000,Saudi Arabia,194.0,Arable land area,4101.0,1992.0,3650.0000
11,United States of America,231.0,Arable land area,4101.0,1997.0,177592.000,Saudi Arabia,194.0,Arable land area,4101.0,1997.0,3639.0000
12,United States of America,231.0,Arable land area,4101.0,2002.0,172977.000,Saudi Arabia,194.0,Arable land area,4101.0,2002.0,3600.0000
13,United States of America,231.0,Arable land area,4101.0,2007.0,161880.000,Saudi Arabia,194.0,Arable land area,4101.0,2007.0,3446.0000
14,United States of America,231.0,Arable land area,4101.0,2012.0,155108.000,Saudi Arabia,194.0,Arable land area,4101.0,2012.0,3117.0000
15,United States of America,231.0,Arable land area,4101.0,2014.0,154605.000,Saudi Arabia,194.0,Arable land area,4101.0,2014.0,3502.0000
16,United States of America,231.0,Permanent crops area,4102.0,1982.0,2034.000,Saudi Arabia,194.0,Permanent crops area,4102.0,1982.0,78.0000
17,United States of America,231.0,Permanent crops area,4102.0,1987.0,2034.000,Saudi Arabia,194.0,Permanent crops area,4102.0,1987.0,80.0000
18,United States of America,231.0,Permanent crops area,4102.0,1992.0,2100.000,Saudi Arabia,194.0,Permanent crops area,4102.0,1992.0,96.0000
19,United States of America,231.0,Permanent crops area,4102.0,1997.0,2500.000,Saudi Arabia,194.0,Permanent crops area,4102.0,1997.0,146.0000
20,United States of America,231.0,Permanent crops area,4102.0,2002.0,2730.000,Saudi Arabia,194.0,Permanent crops area,4102.0,2002.0,193.0000
21,United States of America,231.0,Permanent crops area,4102.0,2007.0,2600.000,Saudi Arabia,194.0,Permanent crops area,4102.0,2007.0,229.0000
22,United States of America,231.0,Permanent crops area,4102.0,2012.0,2600.000,Saudi Arabia,194.0,Permanent crops area,4102.0,2012.0,228.0000
23,United States of America,231.0,Permanent crops area,4102.0,2014.0,2600.000,Saudi Arabia,194.0,Permanent crops area,4102.0,2014.0,145.2000
24,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1982.0,189799.000,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1982.0,2068.0000
25,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1987.0,187776.000,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1987.0,2980.0000
26,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1992.0,186180.000,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1992.0,3746.0000
27,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,1997.0,180092.000,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,1997.0,3785.0000
28,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,2002.0,175707.000,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,2002.0,3793.0000
29,United States of America,231.0,Cultivated area (arable land + permanent crops),4103.0,2007.0,164480.000,Saudi Arabia,194.0,Cultivated area (arable land + permanent crops),4103.0,2007.0,3675.0000
...,...,...,...,...,...,...,...,...,...,...,...,...
481,United States of America,231.0,Agricultural water withdrawal as % of total re...,4273.0,2005.0,6.253,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Citrus,4362.0,1999.0,8.0280
482,United States of America,231.0,Agricultural water withdrawal as % of total re...,4273.0,2010.0,5.705,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Citrus,4362.0,2006.0,10.8500
483,United States of America,231.0,SDG 6.4.2. Water Stress,4550.0,1980.0,27.950,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Oil palm,4370.0,1992.0,2.7000
484,United States of America,231.0,SDG 6.4.2. Water Stress,4550.0,1990.0,25.110,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Other...,4378.0,1992.0,95.5000
485,United States of America,231.0,SDG 6.4.2. Water Stress,4550.0,2000.0,25.570,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Other...,4378.0,1999.0,175.5000
486,United States of America,231.0,SDG 6.4.2. Water Stress,4550.0,2005.0,25.840,Saudi Arabia,194.0,Harvested irrigated permanent crop area: Other...,4378.0,2006.0,190.8000
487,United States of America,231.0,SDG 6.4.2. Water Stress,4550.0,2010.0,22.610,Saudi Arabia,194.0,% of total grain production irrigated,4329.0,1992.0,100.0000
488,United States of America,231.0,Area equipped for full control irrigation: sur...,4308.0,2007.0,12696.000,Saudi Arabia,194.0,Total cultivated area drained,4300.0,2007.0,10.8500
489,United States of America,231.0,Area equipped for full control irrigation: sur...,4308.0,2012.0,12078.000,Saudi Arabia,194.0,% of total cultivated area drained,4305.0,1992.0,1.1740
490,United States of America,231.0,Area equipped for full control irrigation: spr...,4309.0,2005.0,12333.000,Saudi Arabia,194.0,% of total cultivated area drained,4305.0,2007.0,0.2952
491,United States of America,231.0,Area equipped for full control irrigation: spr...,4309.0,2010.0,12780.000,Saudi Arabia,194.0,Area waterlogged by irrigation,4401.0,1980.0,15.0000
492,United States of America,231.0,Area equipped for full control irrigation: loc...,4310.0,2005.0,1615.000,Saudi Arabia,194.0,Flood occurrence (WRI),4543.0,2013.0,1.2000
493,United States of America,231.0,Area equipped for full control irrigation: loc...,4310.0,2010.0,1850.000,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,1992.0,92.3000
494,United States of America,231.0,Area equipped for full control irrigation: total,4311.0,1982.0,26888.000,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,1997.0,94.0000
495,United States of America,231.0,Area equipped for full control irrigation: total,4311.0,1987.0,26667.000,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2002.0,95.7000
496,United States of America,231.0,Area equipped for full control irrigation: total,4311.0,1992.0,27012.000,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2007.0,97.0000
497,United States of America,231.0,Area equipped for full control irrigation: total,4311.0,1997.0,27070.000,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2012.0,97.0000
498,United States of America,231.0,Area equipped for full control irrigation: total,4311.0,2002.0,26937.000,Saudi Arabia,194.0,Total population with access to safe drinking-...,4114.0,2015.0,97.0000
499,United States of America,231.0,Area equipped for full control irrigation: total,4311.0,2007.0,26644.000,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,1992.0,92.3000
500,United States of America,231.0,Area equipped for full control irrigation: total,4311.0,2012.0,26708.000,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,1997.0,94.0000
501,United States of America,231.0,Area equipped for full control irrigation: act...,4461.0,1997.0,22779.000,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2002.0,95.7000
502,United States of America,231.0,Area equipped for full control irrigation: act...,4461.0,2002.0,22384.000,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2007.0,97.0000
503,United States of America,231.0,Area equipped for full control irrigation: act...,4461.0,2007.0,22905.000,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2012.0,97.0000
504,United States of America,231.0,Area equipped for full control irrigation: act...,4461.0,2012.0,22590.000,Saudi Arabia,194.0,Rural population with access to safe drinking-...,4115.0,2015.0,97.0000
505,United States of America,231.0,% of area equipped for full control irrigation...,4463.0,1997.0,84.150,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,1992.0,92.3000
506,United States of America,231.0,% of area equipped for full control irrigation...,4463.0,2002.0,83.100,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,1997.0,94.0000
507,United States of America,231.0,% of area equipped for full control irrigation...,4463.0,2007.0,85.970,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2002.0,95.7000
508,United States of America,231.0,% of area equipped for full control irrigation...,4463.0,2012.0,84.580,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2007.0,97.0000
509,United States of America,231.0,Area equipped for irrigation: total,4313.0,1982.0,26888.000,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2012.0,97.0000
510,United States of America,231.0,Area equipped for irrigation: total,4313.0,1987.0,26667.000,Saudi Arabia,194.0,Urban population with access to safe drinking-...,4116.0,2015.0,97.0000